CREATE TABLE GameData (
musicVolume INTEGER UNIQUE NOT NULL,
sfxVolume INTEGER UNIQUE NOT NULL,
controllerEnabled INTEGER UNIQUE NOT NULL,
lightingEnabled INTEGER UNIQUE NOT NULL,
aaEnabled INTEGER UNIQUE NOT NULL,
brightness INTEGER UNIQUE NOT NULL,
controllerSensitvity INTEGER UNIQUE NOT NULL,
playerPos INTEGER UNIQUE NOT NULL,
currentLevel INTEGER UNIQUE NOT NULL,
)