CREATE TABLE GameData (
_id INTEGER PRIMARY KEY AUTOINCREMENT,
musicVolume INTEGER NOT NULL,
sfxVolume INTEGER NOT NULL,
controllerEnabled INTEGER NOT NULL,
lightingEnabled INTEGER NOT NULL,
aaEnabled INTEGER NOT NULL,
brightness INTEGER NOT NULL,
controllerSensitivity INTEGER NOT NULL,
playerPos INTEGER NOT NULL,
currentLevel INTEGER NOT NULL
)